### ISSUE TITLE
Incorrect forms for male with firstname suffix -я

### ISSUE THREAD

**Issue by pomnikita** [petrovich/petrovich-ruby#36]
Ех: Илья, Добрыня

possible fix

``` yaml
- gender: male
      test: [я]
      mods: [-и, -е, -ю, -ей, -е]
```
